# Generated by Django 4.2.5 on 2023-09-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='title1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
