# Generated by Django 4.2.5 on 2023-09-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_settings_title1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Основные Настройки', 'verbose_name_plural': 'Основная Настройка'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title1',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
