# Generated by Django 4.2.5 on 2023-09-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_settings_options_alter_settings_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='title1',
        ),
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_url',
            field=models.URLField(default=1, verbose_name='instagram url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo_image/', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Тел номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp_url',
            field=models.URLField(default=1, verbose_name='Whatsapp url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='youtube_url',
            field=models.URLField(default=1, verbose_name='youtube url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
